package kz.services.romshop.models;

public enum Region {
    BREST, VITEBSK, GOMEL, GRODNO, MINSK, MINSKIY, MOGILEV, //Беларусь
    ABKHAZIA, AJARIA, GURIA, IMERETI, KAKHETI, KVEMOKARTLI, MTSKHETAMTIANETI,
    RACHALECHKUMIANDKVEMOSVANET, SAMEGRELOZEMOSVANETI, SAMSKHEJAVAKHETI,
    SHIDAKARTLI, TBILISI, //Грузия
    AKMOLINSKIY, AKTUBINSKIY, ALMATINSKIY, ALMATY, ASTANA, ATIRAYSKIY,
    BAIKONYR, ORIENTALKAZAKHSTAN, JAMBYLSKIY, WESTKAZAKHSTAN, KARAGANDINSKIY,
    KOSTANASKIY, KYZILORDINSKIY, MANGISTAYSKIY, PAVLODARSKIY, NORTHKAZAKHSTAN,
    SOUTHKAZAKHSTAN, //Казахстан
    BATKEN, BISHKEK, CHU, JALALABAD, NARYN, OSH, TALAS, YSYKKOL, //Киргизия
    BELGOROD, BRYANSK, VLADIMIR, VOLGOGRAD, VOLOGDA, VORONEZH, IVANOVO, IRKUTSK,
    KALININGRAD, KALUGA, KEMEROVO, KURGAN, KURSK, LENINGRAD, LIPETSK, MAGADAN,
    MOSCOW, MURMANSK, NIZHNYNOVGOROD, NOVGOROD, NOVOSIBIRSK, OMSK, ORENBURG,
    OREL, PENZA, PSKOV, ROSTOV, RYAZAN, SAMARA, SARATOV, SAKHALIN, SVERDLOVSK,
    SMOLYANINOVSKY, TAMBOV, TVER, TOMSK, TULA, TYUMEN, ULYANOVSK, CHELYABINSK,
    CHECHNYA, CHUVASHIA, CHUKOTKA, YAMALNENETS, YAROSLAVL, //Россия
    ANDIJON, BUXORO, FARGONA, JIZZAX, NAMANGAN, NAVOIY, QUASHDARIO,
    QORAQALPOGISTON, SAMARQAND, SIRDARYO, SURXONDARYO, TOSHKENT, TOSHENTSKIY,
    XORAZM, //Узбекистан
    VINNYTSIA, VOLYN, DNIPROPETROVSK, DONETSK, ZHYTOMYR, ZAKARPATTIA, ZAPORIZHIA,
    IVANOFRANKIVSK, KYIVCITY, KYIV, KIROVOHRAD, LUGANSK, LVOV, MYKOLAIV, ODESSA,
    POLTAVA, RIVNE, SUMY, TERNOPIL, KHERSON, KHMELNYTSKY, CHERKASY, CHERNIVTSI,
    CHERNIHIV //Украина
}
