java:
  runtime:
    version: 17

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop }
    username: ${SPRING_DATASOURCE_USERNAME:postgres }
    password: ${SPRING_DATASOURCE_PASSWORD:komka123 }
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: false

token:
  signIn:
    key: 9a4f2c8d1b3a1e6f46a8a0b3f267d8b1d5e6f3c8a9a2b5f8e3a9c8b5f6v8a3d9

paypal:
  mode: sandbox
  client:
    id: AdKVESErqhbcfdqsLkClpYrzRun71w81FcOFQ8ggYOL5CCoGn4UMeXnL7o-SM9iF3pABzHg23ojAtlL6
    secret: EEoJNLeJAS4HV5qCoTB1ubBLliOVJ1cO0KV_t19_5H8hsSNZMM34oCiXUmUYBiQP8jMELP93wOO-z5gb
