spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shop }
    username: ${SPRING_DATASOURCE_USERNAME:postgres }
    password: ${SPRING_DATASOURCE_PASSWORD:komka123 }
    hikari:
      auto-commit: false
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: false

token:
  signIn:
    key: 9a4f2c8d1b3a1e6f46a8a0b3f267d8b1d5e6f3c8a9a2b5f8e3a9c8b5f6v8a3d9

paypal:
  mode: sandbox
  client:
    id: ATyCbd03w_xm-nM3qCsVvVCP6UJirQFzfG7jVKcyjc5SxF0aipKb3zwzir_gEY3mNe4Y3WlkXraUBQTK
    secret: EMjViO3h715cquaw-vZZZqDuLVxqc_ZmlAFSdKITkE7qBhskJnyAb1erzEDXf0GRGhLjyfM9DpIJXGgV
